/**
 * CSS Builder: PostCSS compilation + per-component CSS splitting.
 *
 * Combines three steps:
 * 1. Run PostCSS to compile Tailwind CSS
 * 2. Extract base variables and write to static resource
 * 3. Parse compiled CSS and split utility rules into per-component files
 *
 * Base variables (--tw-*) live in the static resource and are loaded
 * once per component by tailwindMixin via loadStyle. Per-component
 * CSS files contain only the utility class rules each component uses.
 */

import { execSync } from 'node:child_process';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import postcss from 'postcss';

// ── Types ───────────────────────────────────────────────────

interface RuleEntry {
  ruleText: string;
  wrapperName: string | null;
  wrapperParams: string | null;
}

interface ParseResult {
  baseString: string;
  classMap: Map<string, RuleEntry[]>;
}

export interface SplitResult {
  component: string;
  classesFound: number;
  rulesIncluded: number;
  outputBytes: number;
  cssPath: string;
}

export interface BuildResult {
  results: SplitResult[];
  writtenPaths: string[];
  baseBlockBytes: number;
}

// ── Marker ──────────────────────────────────────────────────

const MARKER = '/* === GENERATED BY TAILWIND SPLITTER — DO NOT EDIT BELOW === */';

const SCRIPT_EXTENSIONS = ['.ts', '.js'];

const DEFAULT_EXCLUDE = new Set([
  'tailwindMixin',
  'tailwindUtils',
  'cssLibTailwind',
]);

// ── PostCSS Compilation ─────────────────────────────────────

export function compileCss(
  cwd: string,
  inputPath: string,
  outputPath: string,
  production = false,
): void {
  const env = production ? 'NODE_ENV=production ' : '';
  try {
    execSync(`${env}npx postcss ${inputPath} -o ${outputPath}`, {
      cwd,
      stdio: 'pipe',
    });
  } catch (err) {
    const stderr =
      err instanceof Error && 'stderr' in err
        ? String((err as { stderr: unknown }).stderr).trim()
        : '';
    const detail = stderr || (err instanceof Error ? err.message : String(err));
    throw new Error(`PostCSS compilation failed:\n${detail}`);
  }
}

// ── CssSplitter Class ───────────────────────────────────────

export class CssSplitter {
  private readonly lwcDir: string;
  private readonly staticResourcePath: string;
  private readonly excludeComponents: Set<string>;

  private classMap = new Map<string, RuleEntry[]>();
  private baseString = '';

  constructor(
    lwcDir: string,
    staticResourcePath: string,
    excludeComponents: Set<string> = DEFAULT_EXCLUDE,
  ) {
    this.lwcDir = lwcDir;
    this.staticResourcePath = staticResourcePath;
    this.excludeComponents = excludeComponents;
  }

  async run(compiledCssPath: string): Promise<BuildResult> {
    const fullCss = await readFile(compiledCssPath, 'utf-8');

    const { baseString, classMap } = this.parse(fullCss);
    this.baseString = baseString;
    this.classMap = classMap;

    await writeFile(this.staticResourcePath, baseString, 'utf-8');
    const baseBlockBytes = Buffer.byteLength(baseString, 'utf-8');

    const components = await this.discoverComponents();

    const results: SplitResult[] = [];
    const writtenPaths: string[] = [];

    for (const comp of components) {
      const usedClasses = await this.extractComponentClasses(comp.dir, comp.name);
      if (usedClasses.size === 0) continue;

      const generatedCss = this.buildComponentCss(usedClasses);

      let rulesIncluded = 0;
      for (const cls of usedClasses) {
        if (this.classMap.has(cls)) rulesIncluded++;
      }

      const cssPath = await this.writeComponentCss(comp.dir, comp.name, generatedCss);
      writtenPaths.push(cssPath);

      results.push({
        component: comp.name,
        classesFound: usedClasses.size,
        rulesIncluded,
        outputBytes: Buffer.byteLength(generatedCss, 'utf-8'),
        cssPath,
      });
    }

    return { results, writtenPaths, baseBlockBytes };
  }

  // ── Parsing ─────────────────────────────────────────────

  private parse(cssString: string): ParseResult {
    const root = postcss.parse(cssString);
    const baseNodes: postcss.ChildNode[] = [];
    const classMap = new Map<string, RuleEntry[]>();

    let passedBase = false;
    for (const node of root.nodes) {
      if (!passedBase) {
        if (node.type === 'rule' && this.isBaseRule(node)) {
          baseNodes.push(node);
          continue;
        }
        if (node.type === 'comment') {
          baseNodes.push(node);
          continue;
        }
        passedBase = true;
      }

      if (node.type === 'rule') {
        const cls = this.extractClassFromSelector(node.selector);
        if (cls) {
          if (!classMap.has(cls)) classMap.set(cls, []);
          classMap.get(cls)!.push({
            ruleText: node.toString(),
            wrapperName: null,
            wrapperParams: null,
          });
        }
      } else if (node.type === 'atrule' && node.nodes) {
        for (const child of node.nodes) {
          if (child.type === 'rule') {
            const cls = this.extractClassFromSelector(child.selector);
            if (cls) {
              if (!classMap.has(cls)) classMap.set(cls, []);
              classMap.get(cls)!.push({
                ruleText: child.toString(),
                wrapperName: node.name,
                wrapperParams: node.params,
              });
            }
          }
        }
      }
    }

    const baseString = baseNodes.map((n) => n.toString()).join('\n');
    return { baseString, classMap };
  }

  private extractClassFromSelector(selector: string): string | null {
    const match = selector.match(/\.((?:[a-zA-Z0-9_-]|\\.)+)/);
    if (!match) return null;
    return match[1].replace(/\\(.)/g, '$1');
  }

  private isBaseRule(node: postcss.Rule): boolean {
    const sel = node.selector.replace(/\s+/g, ' ').trim();
    if (sel.includes('.')) return false;
    if (!/^[*,:>\s~+\w()-]+$/.test(sel.replace(/::/g, '').replace(/:/g, ''))) return false;
    return node.nodes.every(
      (n) => n.type === 'decl' && n.prop.startsWith('--tw-'),
    );
  }

  // ── Class Extraction ──────────────────────────────────────

  private async discoverComponents(): Promise<Array<{ name: string; dir: string }>> {
    const entries = await readdir(this.lwcDir, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory() && !this.excludeComponents.has(e.name))
      .map((e) => ({ name: e.name, dir: path.join(this.lwcDir, e.name) }));
  }

  private async extractComponentClasses(
    componentDir: string,
    componentName: string,
  ): Promise<Set<string>> {
    const classes = new Set<string>();

    // HTML
    try {
      const html = await readFile(path.join(componentDir, `${componentName}.html`), 'utf-8');
      for (const cls of this.extractClassesFromHtml(html)) {
        classes.add(cls);
      }
    } catch {
      // No HTML file
    }

    // Script (.ts / .js)
    for (const ext of SCRIPT_EXTENSIONS) {
      try {
        const script = await readFile(path.join(componentDir, `${componentName}${ext}`), 'utf-8');
        for (const cls of this.extractClassesFromScript(script)) {
          classes.add(cls);
        }
        break; // Use the first one found
      } catch {
        // Try next extension
      }
    }

    return classes;
  }

  private extractClassesFromHtml(html: string): Set<string> {
    const classes = new Set<string>();
    const regex = /class\s*=\s*["']([^"']+)["']/g;
    let match;
    while ((match = regex.exec(html)) !== null) {
      for (const cls of match[1].split(/\s+/)) {
        if (cls) classes.add(cls);
      }
    }
    return classes;
  }

  private extractClassesFromScript(source: string): Set<string> {
    const classes = new Set<string>();
    const stringRegex = /(?:'([^'\\]*(?:\\.[^'\\]*)*)'|"([^"\\]*(?:\\.[^"\\]*)*)")/g;
    let match;
    while ((match = stringRegex.exec(source)) !== null) {
      const str = match[1] ?? match[2];
      if (!str) continue;
      for (const token of str.split(/\s+/)) {
        if (token && this.isTailwindClassName(token)) {
          classes.add(token);
        }
      }
    }
    return classes;
  }

  private isTailwindClassName(token: string): boolean {
    if (token.length < 2) return false;
    if (token.includes('/')) return false;
    if (token.startsWith('@')) return false;
    if (/[a-z][A-Z]/.test(token)) return false;
    return /^[a-z!-][\w./:[\]-]*$/.test(token);
  }

  // ── Per-Component CSS Building ────────────────────────────

  private buildComponentCss(usedClasses: Set<string>): string {
    const standaloneRules: string[] = [];
    const mediaGroups = new Map<string, string[]>();

    for (const cls of usedClasses) {
      const entries = this.classMap.get(cls);
      if (!entries) continue;

      for (const entry of entries) {
        if (entry.wrapperName) {
          const key = `@${entry.wrapperName} ${entry.wrapperParams}`;
          if (!mediaGroups.has(key)) mediaGroups.set(key, []);
          mediaGroups.get(key)!.push(entry.ruleText);
        } else {
          standaloneRules.push(entry.ruleText);
        }
      }
    }

    const parts: string[] = [];

    for (const rule of standaloneRules) {
      parts.push(rule);
    }

    for (const [wrapper, rules] of mediaGroups) {
      parts.push(`${wrapper} {\n${rules.join('\n')}\n}`);
    }

    return parts.join('\n');
  }

  private async writeComponentCss(
    componentDir: string,
    componentName: string,
    generatedCss: string,
  ): Promise<string> {
    const cssPath = path.join(componentDir, `${componentName}.css`);
    let existingContent = '';

    try {
      existingContent = await readFile(cssPath, 'utf-8');
    } catch {
      // No existing CSS file
    }

    const markerIndex = existingContent.indexOf(MARKER);
    let handWritten: string;
    if (markerIndex !== -1) {
      handWritten = existingContent.substring(0, markerIndex).trimEnd();
    } else {
      handWritten = existingContent.trimEnd();
    }

    const output = handWritten
      ? `${handWritten}\n\n${MARKER}\n${generatedCss}\n`
      : `${MARKER}\n${generatedCss}\n`;

    await writeFile(cssPath, output, 'utf-8');
    return cssPath;
  }
}

// ── Legacy wrapper for backward compatibility ───────────────

export async function splitCss(
  compiledCssPath: string,
  lwcDir: string,
  staticResourcePath: string,
): Promise<BuildResult> {
  const splitter = new CssSplitter(lwcDir, staticResourcePath);
  return splitter.run(compiledCssPath);
}
