/**
 * CSS Builder: PostCSS compilation + per-component CSS splitting.
 *
 * Combines two steps:
 * 1. Run PostCSS to compile Tailwind CSS
 * 2. Parse compiled CSS and split into per-component files
 *
 * Includes smart base block optimization — only includes the ~2.6 KB
 * Tailwind CSS variable block if a component uses classes that need it.
 */

import { execSync } from 'node:child_process';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import postcss from 'postcss';

// ── Types ───────────────────────────────────────────────────

interface RuleEntry {
  ruleText: string;
  wrapperName: string | null;
  wrapperParams: string | null;
}

interface ParseResult {
  baseString: string;
  classMap: Map<string, RuleEntry[]>;
}

export interface SplitResult {
  component: string;
  classesFound: number;
  rulesIncluded: number;
  outputBytes: number;
  cssPath: string;
  baseIncluded: boolean;
}

export interface BuildResult {
  results: SplitResult[];
  writtenPaths: string[];
}

// ── CSS Variable Patterns ───────────────────────────────────

/**
 * Patterns in compiled CSS rule text that indicate the rule depends
 * on --tw-* CSS variables from the base block.
 *
 * If a component uses any class whose compiled CSS contains one of
 * these patterns, the base block must be included.
 */
const TW_VAR_PATTERN = /var\(--tw-/;

// ── Marker ──────────────────────────────────────────────────

const MARKER = '/* === GENERATED BY TAILWIND SPLITTER — DO NOT EDIT BELOW === */';

// ── PostCSS Compilation ─────────────────────────────────────

export function compileCss(
  cwd: string,
  inputPath: string,
  outputPath: string,
  production = false,
): void {
  const env = production ? 'NODE_ENV=production ' : '';
  execSync(`${env}npx postcss ${inputPath} -o ${outputPath}`, {
    cwd,
    stdio: 'pipe',
  });
}

// ── CSS Parsing ─────────────────────────────────────────────

function extractClassFromSelector(selector: string): string | null {
  const match = selector.match(/\.((?:[a-zA-Z0-9_-]|\\.)+)/);
  if (!match) return null;
  return match[1].replace(/\\(.)/g, '$1');
}

function isBaseRule(node: postcss.Rule): boolean {
  const sel = node.selector.replace(/\s+/g, ' ').trim();
  if (sel.includes('.')) return false;
  if (!/^[*,:>\s~+\w()-]+$/.test(sel.replace(/::/g, '').replace(/:/g, ''))) return false;
  return node.nodes.every(
    (n) => n.type === 'decl' && n.prop.startsWith('--tw-'),
  );
}

function parseTailwindCss(cssString: string): ParseResult {
  const root = postcss.parse(cssString);
  const baseNodes: postcss.ChildNode[] = [];
  const classMap = new Map<string, RuleEntry[]>();

  let passedBase = false;
  for (const node of root.nodes) {
    if (!passedBase) {
      if (node.type === 'rule' && isBaseRule(node)) {
        baseNodes.push(node);
        continue;
      }
      if (node.type === 'comment') {
        baseNodes.push(node);
        continue;
      }
      passedBase = true;
    }

    if (node.type === 'rule') {
      const cls = extractClassFromSelector(node.selector);
      if (cls) {
        if (!classMap.has(cls)) classMap.set(cls, []);
        classMap.get(cls)!.push({
          ruleText: node.toString(),
          wrapperName: null,
          wrapperParams: null,
        });
      }
    } else if (node.type === 'atrule' && node.nodes) {
      for (const child of node.nodes) {
        if (child.type === 'rule') {
          const cls = extractClassFromSelector(child.selector);
          if (cls) {
            if (!classMap.has(cls)) classMap.set(cls, []);
            classMap.get(cls)!.push({
              ruleText: child.toString(),
              wrapperName: node.name,
              wrapperParams: node.params,
            });
          }
        }
      }
    }
  }

  const baseString = baseNodes.map((n) => n.toString()).join('\n');
  return { baseString, classMap };
}

// ── Class Extraction ────────────────────────────────────────

function isTailwindClassName(token: string): boolean {
  if (token.length < 2) return false;
  if (token.includes('/')) return false;
  if (token.startsWith('@')) return false;
  if (/[a-z][A-Z]/.test(token)) return false;
  return /^[a-z!-][\w./:[\]-]*$/.test(token);
}

function extractClassesFromHtml(html: string): Set<string> {
  const classes = new Set<string>();
  const regex = /class\s*=\s*["']([^"']+)["']/g;
  let match;
  while ((match = regex.exec(html)) !== null) {
    for (const cls of match[1].split(/\s+/)) {
      if (cls) classes.add(cls);
    }
  }
  return classes;
}

function extractClassesFromJs(jsSource: string): Set<string> {
  const classes = new Set<string>();
  const stringRegex = /(?:'([^'\\]*(?:\\.[^'\\]*)*)'|"([^"\\]*(?:\\.[^"\\]*)*)")/g;
  let match;
  while ((match = stringRegex.exec(jsSource)) !== null) {
    const str = match[1] ?? match[2];
    if (!str) continue;
    for (const token of str.split(/\s+/)) {
      if (token && isTailwindClassName(token)) {
        classes.add(token);
      }
    }
  }
  return classes;
}

async function extractComponentClasses(
  componentDir: string,
  componentName: string,
): Promise<Set<string>> {
  const classes = new Set<string>();

  const htmlPath = path.join(componentDir, `${componentName}.html`);
  const jsPath = path.join(componentDir, `${componentName}.js`);

  try {
    const html = await readFile(htmlPath, 'utf-8');
    for (const cls of extractClassesFromHtml(html)) {
      classes.add(cls);
    }
  } catch {
    // No HTML file
  }

  try {
    const js = await readFile(jsPath, 'utf-8');
    for (const cls of extractClassesFromJs(js)) {
      classes.add(cls);
    }
  } catch {
    // No JS file
  }

  return classes;
}

// ── Per-Component CSS Building ──────────────────────────────

function buildComponentCss(
  usedClasses: Set<string>,
  classMap: Map<string, RuleEntry[]>,
  baseString: string,
): { css: string; baseIncluded: boolean } {
  const parts: string[] = [];
  const standaloneRules: string[] = [];
  const mediaGroups = new Map<string, string[]>();

  // Collect matched rules
  let needsBase = false;

  for (const cls of usedClasses) {
    const entries = classMap.get(cls);
    if (!entries) continue;

    for (const entry of entries) {
      // Check if this rule references --tw-* variables
      if (TW_VAR_PATTERN.test(entry.ruleText)) {
        needsBase = true;
      }

      if (entry.wrapperName) {
        const key = `@${entry.wrapperName} ${entry.wrapperParams}`;
        if (!mediaGroups.has(key)) mediaGroups.set(key, []);
        mediaGroups.get(key)!.push(entry.ruleText);
      } else {
        standaloneRules.push(entry.ruleText);
      }
    }
  }

  // Only include the base block if at least one rule needs --tw-* variables
  if (needsBase && baseString) {
    parts.push(baseString);
  }

  for (const rule of standaloneRules) {
    parts.push(rule);
  }

  for (const [wrapper, rules] of mediaGroups) {
    parts.push(`${wrapper} {\n${rules.join('\n')}\n}`);
  }

  return { css: parts.join('\n'), baseIncluded: needsBase };
}

async function writeComponentCss(
  componentDir: string,
  componentName: string,
  generatedCss: string,
): Promise<string> {
  const cssPath = path.join(componentDir, `${componentName}.css`);
  let existingContent = '';

  try {
    existingContent = await readFile(cssPath, 'utf-8');
  } catch {
    // No existing CSS file
  }

  const markerIndex = existingContent.indexOf(MARKER);
  let handWritten: string;
  if (markerIndex !== -1) {
    handWritten = existingContent.substring(0, markerIndex).trimEnd();
  } else {
    handWritten = existingContent.trimEnd();
  }

  const output = handWritten
    ? `${handWritten}\n\n${MARKER}\n${generatedCss}\n`
    : `${MARKER}\n${generatedCss}\n`;

  await writeFile(cssPath, output, 'utf-8');
  return cssPath;
}

// ── Main Split Function ─────────────────────────────────────

const EXCLUDE_COMPONENTS = new Set([
  'tailwindElement',
  'tailwindUtils',
  'cssLibTailwind',
]);

export async function splitCss(
  tailwindCssPath: string,
  lwcDir: string,
): Promise<BuildResult> {
  // 1. Read compiled CSS
  const fullCss = await readFile(tailwindCssPath, 'utf-8');

  // 2. Parse
  const { baseString, classMap } = parseTailwindCss(fullCss);

  // 3. Discover components
  const entries = await readdir(lwcDir, { withFileTypes: true });
  const components = entries
    .filter((e) => e.isDirectory() && !EXCLUDE_COMPONENTS.has(e.name))
    .map((e) => ({ name: e.name, dir: path.join(lwcDir, e.name) }));

  // 4. Process each component
  const results: SplitResult[] = [];
  const writtenPaths: string[] = [];

  for (const comp of components) {
    const usedClasses = await extractComponentClasses(comp.dir, comp.name);
    if (usedClasses.size === 0) continue;

    const { css: generatedCss, baseIncluded } = buildComponentCss(
      usedClasses,
      classMap,
      baseString,
    );

    let rulesIncluded = 0;
    for (const cls of usedClasses) {
      if (classMap.has(cls)) rulesIncluded++;
    }

    const cssPath = await writeComponentCss(comp.dir, comp.name, generatedCss);
    writtenPaths.push(cssPath);

    results.push({
      component: comp.name,
      classesFound: usedClasses.size,
      rulesIncluded,
      outputBytes: Buffer.byteLength(generatedCss, 'utf-8'),
      cssPath,
      baseIncluded,
    });
  }

  return { results, writtenPaths };
}
