/**
 * Runtime LWC templates: tailwindElement, tailwindUtils, static resource meta XML.
 */

export function tailwindElementJs() {
    return `import { LightningElement } from 'lwc';
import { loadStyle } from 'lightning/platformResourceLoader';
import TAILWIND from '@salesforce/resourceUrl/tailwind';

/**
 * Base class for LWC components that use Tailwind CSS.
 *
 * Handles Tailwind CSS loading automatically — no boilerplate needed.
 * Uses the Template Method pattern so child classes can safely extend
 * lifecycle behavior without breaking CSS injection.
 *
 * If your component uses per-component split CSS (generated by the splitter),
 * set \`static useSplitCss = true\` to skip loadStyle — the CSS is already
 * in your component's .css file and auto-loaded by LWC.
 *
 * @example
 * import TailwindElement from 'c/tailwindElement';
 *
 * export default class MyComponent extends TailwindElement {
 *     static useSplitCss = true; // CSS comes from component .css file
 *
 *     onInit() {
 *         // runs on connectedCallback
 *     }
 * }
 */
export default class TailwindElement extends LightningElement {
    _twLoaded = false;

    connectedCallback() {
        this.onInit();
    }

    renderedCallback() {
        if (!this._twLoaded) {
            this._twLoaded = true;
            // Skip loadStyle if component uses per-component split CSS
            if (!this.constructor.useSplitCss) {
                loadStyle(this, TAILWIND).catch((err) => {
                    console.error('[TailwindElement] Failed to load styles:', err);
                });
            }
            this.onFirstRender();
        }
        this.onRender();
    }

    disconnectedCallback() {
        this.onDisconnect();
    }

    /** Override in child class. Runs on connectedCallback. */
    onInit() {}

    /** Override in child class. Runs once after first render. */
    onFirstRender() {}

    /** Override in child class. Runs on every render cycle. */
    onRender() {}

    /** Override in child class. Runs on disconnectedCallback. */
    onDisconnect() {}
}
`;
}

export function tailwindElementMeta(apiVersion) {
    return `<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>${apiVersion}</apiVersion>
    <isExposed>false</isExposed>
    <description>Base class for Tailwind CSS enabled LWC components</description>
</LightningComponentBundle>
`;
}

export function tailwindUtilsJs() {
    return `/**
 * Utility for composing Tailwind CSS class names in LWC.
 * Works like clsx/classnames from the React ecosystem.
 *
 * @example
 * import { cn } from 'c/tailwindUtils';
 *
 * // Strings
 * cn('px-4 py-2', 'text-white')  // → 'px-4 py-2 text-white'
 *
 * // Conditionals
 * cn('base', isActive && 'bg-brand', !isActive && 'bg-gray-200')
 *
 * // Objects
 * cn('base', { 'bg-brand': isActive, 'opacity-50': isDisabled })
 *
 * // Arrays
 * cn(['px-4', 'py-2'], 'text-white')
 *
 * // Mixed
 * cn('px-4', condition && 'font-bold', { 'text-error': hasError }, ['rounded-md'])
 */
export function cn(...args) {
    const classes = [];

    for (let i = 0; i < args.length; i++) {
        const arg = args[i];
        if (!arg) continue;

        if (typeof arg === 'string') {
            classes.push(arg);
        } else if (Array.isArray(arg)) {
            const inner = cn(...arg);
            if (inner) classes.push(inner);
        } else if (typeof arg === 'object') {
            const keys = Object.keys(arg);
            for (let k = 0; k < keys.length; k++) {
                if (arg[keys[k]]) {
                    classes.push(keys[k]);
                }
            }
        }
    }

    return classes.join(' ');
}
`;
}

export function tailwindUtilsMeta(apiVersion) {
    return `<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>${apiVersion}</apiVersion>
    <isExposed>false</isExposed>
    <description>Utility functions for Tailwind CSS in LWC (cn class helper)</description>
</LightningComponentBundle>
`;
}

export function staticResourceMeta() {
    return `<?xml version="1.0" encoding="UTF-8"?>
<StaticResource xmlns="http://soap.sforce.com/2006/04/metadata">
    <cacheControl>Public</cacheControl>
    <contentType>text/css</contentType>
    <description>Compiled Tailwind CSS utilities</description>
</StaticResource>
`;
}
