/**
 * CSS Writer for the Tailwind CSS Splitter.
 *
 * Merges generated per-component CSS with any existing hand-written CSS
 * in the component's .css file. Uses a marker comment to delineate
 * the generated section from the hand-written section.
 */

import { readFile, writeFile } from 'fs/promises';
import path from 'path';

const MARKER = '/* === GENERATED BY TAILWIND SPLITTER — DO NOT EDIT BELOW === */';

/**
 * Build the generated CSS string for a component.
 *
 * Takes the base block (CSS variable initialization) and the set of
 * CSS rules matching the component's used classes, then assembles
 * them into a single CSS string with @media blocks deduplicated.
 *
 * @param {Set<string>} usedClasses - Class names the component uses
 * @param {Map} classMap - Map from class name to array of rule entries
 * @param {string} baseString - The Tailwind CSS variable base block
 * @returns {string} The generated CSS
 */
export function buildComponentCss(usedClasses, classMap, baseString) {
    const parts = [];

    // 1. Base block (CSS variable initialization)
    if (baseString) {
        parts.push(baseString);
    }

    // 2. Collect matched rules, grouping @media-wrapped rules by their params
    const standaloneRules = [];
    // key: "@name params" → Array<ruleText>
    const mediaGroups = new Map();

    for (const cls of usedClasses) {
        const entries = classMap.get(cls);
        if (!entries) continue;

        for (const entry of entries) {
            if (entry.wrapperName) {
                const key = `@${entry.wrapperName} ${entry.wrapperParams}`;
                if (!mediaGroups.has(key)) mediaGroups.set(key, []);
                mediaGroups.get(key).push(entry.ruleText);
            } else {
                standaloneRules.push(entry.ruleText);
            }
        }
    }

    // 3. Add standalone rules
    for (const rule of standaloneRules) {
        parts.push(rule);
    }

    // 4. Add grouped @media blocks
    for (const [wrapper, rules] of mediaGroups) {
        parts.push(`${wrapper} {\n${rules.join('\n')}\n}`);
    }

    return parts.join('\n');
}

/**
 * Write the generated CSS into a component's .css file,
 * preserving any hand-written CSS above the marker.
 *
 * @param {string} componentDir - Full path to the component directory
 * @param {string} componentName - The component name
 * @param {string} generatedCss - The generated Tailwind CSS to write
 * @returns {Promise<string>} The full path of the written CSS file
 */
export async function writeComponentCss(componentDir, componentName, generatedCss) {
    const cssPath = path.join(componentDir, `${componentName}.css`);
    let existingContent = '';

    try {
        existingContent = await readFile(cssPath, 'utf-8');
    } catch {
        // No existing CSS file — that's fine, we'll create one
    }

    // Split on the marker to preserve hand-written CSS
    const markerIndex = existingContent.indexOf(MARKER);
    let handWritten;
    if (markerIndex !== -1) {
        handWritten = existingContent.substring(0, markerIndex).trimEnd();
    } else {
        handWritten = existingContent.trimEnd();
    }

    // Combine hand-written + marker + generated
    const output = handWritten
        ? `${handWritten}\n\n${MARKER}\n${generatedCss}\n`
        : `${MARKER}\n${generatedCss}\n`;

    await writeFile(cssPath, output, 'utf-8');
    return cssPath;
}

export { MARKER };
