import { LightningElement } from 'lwc';
import { loadStyle } from 'lightning/platformResourceLoader';
import TAILWIND from '@salesforce/resourceUrl/tailwind';

/**
 * Base class for LWC components that use Tailwind CSS.
 *
 * Handles Tailwind CSS loading automatically — no boilerplate needed.
 * Uses the Template Method pattern so child classes can safely extend
 * lifecycle behavior without breaking CSS injection.
 *
 * If your component uses per-component split CSS (generated by the splitter),
 * set `static useSplitCss = true` to skip loadStyle — the CSS is already
 * in your component's .css file and auto-loaded by LWC.
 *
 * @example
 * import TailwindElement from 'c/tailwindElement';
 *
 * export default class MyComponent extends TailwindElement {
 *     static useSplitCss = true; // CSS comes from component .css file
 *
 *     onInit() {
 *         // runs on connectedCallback
 *     }
 * }
 */
export default class TailwindElement extends LightningElement {
    _twLoaded = false;

    connectedCallback() {
        this.onInit();
    }

    renderedCallback() {
        if (!this._twLoaded) {
            this._twLoaded = true;
            // Skip loadStyle if component uses per-component split CSS
            if (!this.constructor.useSplitCss) {
                loadStyle(this, TAILWIND).catch((err) => {
                    console.error('[TailwindElement] Failed to load styles:', err);
                });
            }
            this.onFirstRender();
        }
        this.onRender();
    }

    disconnectedCallback() {
        this.onDisconnect();
    }

    /** Override in child class. Runs on connectedCallback. */
    onInit() {}

    /** Override in child class. Runs once after first render. */
    onFirstRender() {}

    /** Override in child class. Runs on every render cycle. */
    onRender() {}

    /** Override in child class. Runs on disconnectedCallback. */
    onDisconnect() {}
}
